apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "myk-trade-chart.fullname" . }}
  labels:
    {{- include "myk-trade-chart.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
