name: Deploy to k3s

on:
  push:
    branches: []

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: https://${{ env.ENV_NAME }}.test
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}


    - name: Build and push app
      id: build-and-push-app
      uses: docker/build-push-action@v5
      with:
        context: .
        file: deploy/Dockerfile
        no-cache: false
        platforms: linux/amd64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository }}:latest
          ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}

    - uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm -n myk-trade upgrade myk-trade ./myk-trade-chart/ --install --wait --atomic --set image.tag=${{ github.sha }}
        kubeconfig: '${{ secrets.KUBECONFIG }}'
        overrule_existing_kubeconfig: "true"
