name: Deploy to k3s[ovh0]

on:
  push:
    branches:
    - main

env:
  ENV_NAME: main
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: main
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}


    - name: Build and push app
      id: build-and-push-app
      uses: docker/build-push-action@v5
      with:
        context: .
        file: deploy/Dockerfile
        no-cache: false
        platforms: linux/amd64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository }}:latest
          ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: -n myk_trade set image deployment/myk-trade-myk-trade-chart myk-trade=${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
