name: Deploy to k3s[ovh0]

on:
  push:
    branches:
    - main

env:
  ENV_NAME: main
  REGISTRY: ghcr.io
  CONTAINER_NAME: app
  IMAGE_NAME: ${{ github.repository }}


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: main
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push app
      id: build-and-push-app
      uses: docker/build-push-action@v5
      env:
        IMAGE_TAG: ${{ github.sha }}
      with:
        context: .
        file: deploy/Dockerfile
        no-cache: false
        platforms: linux/amd64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ env.REGISTRY }}/orplayground/myk_trade:${{ env.IMAGE_TAG }}
          ${{ env.REGISTRY }}/orplayground/myk_trade:latest
