name: Deploy to k3s

on:
  push:
    branches:
    - main
    - dev

jobs:
  call-deploy-to-k3s-main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-to-k3s.yaml
    with:
      registry: ghcr.io
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}

  call-deploy-to-k3s-dev:
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/deploy-to-k3s.yaml
    with:
      registry: ghcr.io
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
