name: deploy main

on:
  push:
    branches:
    - main

jobs:
  call-deploy-to-k3s:
    uses: ./.github/workflows/deploy-to-k3s.yaml
    with:
      registry: ghcr.io
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
